#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'camera-sim-pub','console_scripts','multi_cam_pub'
__requires__ = 'camera-sim-pub'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('camera-sim-pub', 'console_scripts', 'multi_cam_pub')()
    )
